"""Registry of UOL Účetnictví list endpoints.

Single source of truth: each Endpoint declares its API path, primary key,
the available date filter query-params (empty for full-load-only endpoints),
any nested array fields to explode into child tables, and stable column
names for the parent table (used to seed _collect_columns so the schema is
stable even on zero-row extracts).

PKs, child arrays, date_fields and columns were verified against the live demo
instance (test.demo.uol.cz) and the OpenAPI spec (api.uol.cz/openapi.yaml).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Endpoint:
    name: str
    path: str
    primary_key: list[str]
    date_fields: tuple[str, ...] = ()
    child_arrays: tuple[str, ...] = ()
    columns: tuple[str, ...] = ()


def _ep(
    name: str,
    pk: list[str],
    *,
    date_fields: tuple[str, ...] = (),
    children: tuple[str, ...] = (),
    columns: tuple[str, ...] = (),
) -> Endpoint:
    return Endpoint(
        name=name,
        path=f"v1/{name}",
        primary_key=pk,
        date_fields=date_fields,
        child_arrays=children,
        columns=columns,
    )


_ALL = [
    _ep(
        "sales_invoices",
        ["gid"],
        date_fields=("tax_payment_date_from", "issue_date_from", "due_date_from"),
        children=("items",),
        columns=(
            "accounting_address",
            "buyer_address",
            "bank_account",
            "creator",
            "currency",
            "delivery_address",
            "department",
            "document_recipient_address",
            "linked_doc",
            "logo",
            "modifier",
            "order",
            "contract",
            "shipper",
            "buyer",
            "cancellation_date",
            "constant_symbol",
            "consumption_country_id",
            "created_at",
            "delivery_note",
            "delivery_note_note",
            "delivery_note_text",
            "due_date",
            "exchange_rate",
            "external_id",
            "invoice_id",
            "gid",
            "issue_date",
            "note",
            "payment_method",
            "percent_discount",
            "public_id",
            "rounding",
            "status",
            "send_by_email",
            "send_by_mail",
            "shipping_method",
            "specific_symbol",
            "tax_payment_date",
            "text",
            "total_amount",
            "type",
            "updated_at",
            "variable_symbol",
            "vat1_amount",
            "vat2_amount",
            "vat3_amount",
            "vat_document",
        ),
    ),
    _ep(
        "sales_orders",
        ["order_id"],
        date_fields=("created_at_from", "updated_at_from", "fullfilled_on_from"),
        children=("items",),
        columns=(
            "created_at",
            "updated_at",
            "creator",
            "modifier",
            "accounting_address",
            "buyer_address",
            "document_recipient_address",
            "delivery_address",
            "contact",
            "currency",
            "date_of_receipt",
            "delivery_method",
            "department",
            "percent_discount",
            "external_id",
            "fullfilled_on",
            "group_id",
            "invoicing_method",
            "status",
            "order_id",
            "contract",
            "shipper_id",
            "shipping_method",
            "specific_symbol",
            "payment_method",
            "complete_upon_execution",
            "repeat_start",
            "repeat_interval",
            "next_repeat_time",
            "text",
            "note",
        ),
    ),
    _ep("retails", ["retail_id"], children=("items",)),
    _ep(
        "purchase_invoices",
        ["gid"],
        date_fields=("tax_payment_date_from", "due_date_from", "received_date_from"),
        children=("items",),
        columns=(
            "created_at",
            "updated_at",
            "creator",
            "modifier",
            "seller",
            "currency",
            "department",
            "order",
            "contract",
            "date_of_receipt",
            "due_date",
            "issue_date",
            "tax_payment_date",
            "bank_code",
            "bank_country_id",
            "account_number",
            "reduce_vat_deduction",
            "constant_symbol",
            "percent_discount",
            "external_id",
            "iban",
            "invoice_id",
            "gid",
            "status",
            "isdoc",
            "note",
            "payment_method",
            "exchange_rate",
            "rounding",
            "shipper",
            "shipping_method",
            "specific_symbol",
            "total_amount",
            "type",
            "vat_document",
            "vat1_amount",
            "vat2_amount",
            "vat3_amount",
            "variable_symbol",
            "public_id",
            "linked_doc_number",
        ),
    ),
    _ep("purchase_orders", ["order_id"], children=("items",)),
    _ep("contacts", ["contact_id"], children=("addresses",)),
    _ep("contact_bank_accounts", ["bank_account_id"]),
    _ep("products", ["product_id"]),
    _ep("product_categories", ["type_id"]),
    _ep("price_lists", ["price_list_id"], children=("items",)),
    _ep("my_bank_accounts", ["bank_account_id"]),
    _ep("bank_movements", ["gid"], children=("items",)),
    _ep("bank_movement_items", []),
    _ep("demands_for_payment", ["reminder_id"], children=("items",)),
    _ep("my_companies", ["my_company_id"]),
    _ep("departments", ["department_id"]),
    _ep("contracts", ["contract_id"]),
    _ep("petty_cashes", ["petty_cash_id"]),
    _ep("petty_cash_incomes", ["gid"], children=("items",)),
    _ep("petty_cash_disburstments", ["gid"], children=("items",)),
    _ep(
        "accounting_records",
        ["gid"],
        date_fields=("date_from",),
        columns=(
            "creator",
            "modifier",
            "product",
            "contact",
            "currency",
            "department",
            "contract",
            "doc_type",
            "linked_doc_type",
            "period",
            "debit_account",
            "credit_account",
            "accounting_amount",
            "amount",
            "batch",
            "created_at",
            "date",
            "description",
            "doc_code",
            "doc_number",
            "expiration_date",
            "external_id",
            "generated",
            "gid",
            "id",
            "linked_doc_code",
            "linked_doc_number",
            "quantity",
            "rule_id",
            "serial_numbers",
            "status",
            "updated_at",
        ),
    ),
    _ep(
        "receivables",
        ["invoice_id"],
        date_fields=("last_payment_time_from", "invoice_issue_date_from", "due_date_from", "tax_payment_date_from"),
        children=("payments",),
        columns=(
            "invoice_public_id",
            "contact_id",
            "department_id",
            "invoice_type",
            "currency_id",
            "cancelled",
            "issue_date",
            "due_date",
            "tax_payment_date",
            "invoice_amount",
            "total_amount",
            "total_amount_in_currency",
            "paid_amount",
            "last_payment_date",
            "invoice_id",
            "exchange_rate",
            "department",
            "total_amount_currency_ids",
            "invoice_issue_date",
            "invoice_currency_id",
            "invoice_exchange_rate",
            "last_payment_time",
            "paid_amount_in_currency",
            "paid_amount_currency_ids",
        ),
    ),
    _ep("internal_documents", ["number"], children=("items",)),
    _ep(
        "uploaded_documents",
        ["id"],
        date_fields=("created_at_from",),
        columns=(
            "id",
            "file",
            "state",
            "note",
            "created_at",
            "updated_at",
            "creator",
            "modifier",
        ),
    ),
    _ep("document_templates", ["id"]),
    _ep("currencies", ["currency_id"]),
    _ep("countries", ["country_id"]),
    _ep("predefined_texts", ["predefined_text_id"]),
    _ep("payment_rules", ["gid"]),
]

ENDPOINTS: dict[str, Endpoint] = {e.name: e for e in _ALL}


def get_endpoint(name: str) -> Endpoint:
    return ENDPOINTS[name]


def endpoint_names() -> list[str]:
    return sorted(ENDPOINTS)
